
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.55
distribution_type: module
version: 0.15
name: PITA-Image
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  File::Remove: 0.21
  URI: 0
  Process: 0.16
  File::Spec: 0.80
  File::Which: 0.05
  PITA::Scheme: 0.15
  Carp: 0
  perl: 5.005
  Params::Util: 0.10
  File::Temp: 0
  Config::Tiny: 2.00
  PITA::XML: 0.19
  LWP: 5.69
abstract: PITA Guest Manager for inside system images
