---
abstract: 'PITA Guest Manager for inside system images'
author:
  - 'Adam Kennedy <adamk@cpan.org>, L<http://ali.as/>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PITA::Image
name: PITA-Image
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  Config::Tiny: 2.00
  File::Remove: 0.34
  File::Spec: 0.80
  File::Temp: 0
  File::Which: 0.05
  LWP: 5.69
  PITA::Scheme: 0.42
  PITA::XML: 0.41
  Params::Util: 0.10
  Process: 0.16
  URI: 0
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/PITA-Image
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/PITA-Image
version: 0.42
